"""Write the output artifacts from a :class:`~survey_cleaner.pipeline.ProcessResult`.

Outputs (into ``out_dir``):
- ``cleaned.csv`` (always, unless ``--report-only``)
- ``cleaned.xlsx`` (when ``--xlsx``)
- ``data_dictionary.csv``
- ``quality_report.md``
- ``cleaning_log.json``

The original input file is never modified or overwritten.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import List

import pandas as pd

from survey_cleaner import __version__
from survey_cleaner.pipeline import ProcessResult
from survey_cleaner.types_infer import (
    CATEGORICAL_MAX_UNIQUE,
    MULTISELECT_MIN_DELIM_FRACTION,
    TYPE_THRESHOLD,
)

OUTPUT_FILES = [
    "cleaned.csv",
    "cleaned.xlsx",
    "data_dictionary.csv",
    "quality_report.md",
    "cleaning_log.json",
]

DATA_DICTIONARY_COLUMNS = [
    "original_column",
    "cleaned_column",
    "inferred_type",
    "description",
    "n_missing",
    "pct_missing",
    "n_unique",
    "example_value",
    "is_multiselect",
    "parent_column",
    "option",
    "notes",
]


def write_outputs(result: ProcessResult, out_dir, force: bool = False) -> List[Path]:
    out = Path(out_dir)
    _prepare_out_dir(out, force)

    written: List[Path] = []
    if not result.config.report_only:
        written.append(_write_cleaned_csv(result, out))
        if result.config.write_xlsx:
            written.append(_write_cleaned_xlsx(result, out))
    written.append(_write_data_dictionary(result, out))
    written.append(_write_quality_report(result, out))
    written.append(_write_cleaning_log(result, out))
    return written


def _prepare_out_dir(out: Path, force: bool) -> None:
    out.mkdir(parents=True, exist_ok=True)
    existing = [name for name in OUTPUT_FILES if (out / name).exists()]
    if existing and not force:
        raise FileExistsError(
            f"Output directory '{out}' already contains {existing}. "
            f"Use --force to overwrite."
        )


def _write_cleaned_csv(result: ProcessResult, out: Path) -> Path:
    path = out / "cleaned.csv"
    result.cleaned_df.to_csv(path, index=False)
    return path


def _write_cleaned_xlsx(result: ProcessResult, out: Path) -> Path:
    path = out / "cleaned.xlsx"
    result.cleaned_df.to_excel(path, index=False, engine="openpyxl")
    return path


def _child_meta(result: ProcessResult) -> dict:
    meta = {}
    for col in result.schema.columns:
        for option, child_name in col.split_children:
            meta[child_name] = (col.cleaned_name, option)
    return meta


def _write_data_dictionary(result: ProcessResult, out: Path) -> Path:
    path = out / "data_dictionary.csv"
    child_meta = _child_meta(result)
    rows = []
    for col in result.schema.columns:
        parent, option = child_meta.get(col.cleaned_name, ("", ""))
        rows.append(
            {
                "original_column": col.original_name,
                "cleaned_column": col.cleaned_name,
                "inferred_type": col.inferred_type,
                "description": col.original_name,
                "n_missing": col.n_missing,
                "pct_missing": col.pct_missing,
                "n_unique": col.n_unique,
                "example_value": col.example_value,
                "is_multiselect": col.is_multiselect,
                "parent_column": parent,
                "option": option,
                "notes": "; ".join(col.notes),
            }
        )
    pd.DataFrame(rows, columns=DATA_DICTIONARY_COLUMNS).to_csv(path, index=False)
    return path


def _esc(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _write_quality_report(result: ProcessResult, out: Path) -> Path:
    path = out / "quality_report.md"
    lr = result.load_result
    v = result.validation
    lines: List[str] = []

    lines.append("# Cleaning quality report")
    lines.append("")
    lines.append(f"Generated by survey-data-cleaner v{__version__}.")
    lines.append("")

    lines.append("## Source")
    lines.append("")
    lines.append(f"- **File:** `{lr.source_path}`")
    lines.append(f"- **Type:** {lr.kind}")
    if lr.sheet:
        lines.append(f"- **Sheet:** {lr.sheet}")
    if lr.encoding:
        lines.append(f"- **Encoding:** {lr.encoding}")
    if lr.delimiter:
        lines.append(f"- **Delimiter:** `{lr.delimiter}`")
    lines.append(f"- **Detected profile:** {result.profile.name}")
    lines.append(
        f"- **Rows:** {result.n_rows_in} in / {result.n_rows_out} out"
    )
    lines.append(f"- **Columns (cleaned table):** {result.cleaned_df.shape[1]}")
    lines.append("")

    lines.append("## Cleaning summary")
    lines.append("")
    total_std = sum(c.n_missing_standardised for c in result.schema.columns)
    n_split = sum(1 for c in result.schema.columns if c.split_children)
    lines.append(
        f"- Missing tokens treated as blank: {', '.join(repr(t) for t in result.missing_tokens)}"
    )
    lines.append(f"- Cells standardised to missing: {total_std}")
    lines.append(f"- Multi-select columns split: {n_split}")
    lines.append(
        f"- Duplicate rows: {v.n_duplicate_rows} found, "
        f"{result.dropped_duplicate_rows} dropped"
    )
    if result.dropped_empty_columns:
        lines.append(
            f"- Mostly-empty columns dropped: {result.dropped_empty_columns}"
        )
    lines.append("")

    lines.append("## Columns")
    lines.append("")
    lines.append("| Cleaned name | Type | % missing | Unique | Example |")
    lines.append("| --- | --- | ---: | ---: | --- |")
    for col in result.schema.columns:
        if col.dropped:
            continue
        lines.append(
            f"| {_esc(col.cleaned_name)} | {col.inferred_type} | "
            f"{col.pct_missing * 100:.1f}% | {col.n_unique} | "
            f"{_esc(col.example_value)} |"
        )
    lines.append("")

    lines.append("## Issues & warnings")
    lines.append("")
    if v.empty_columns:
        names = ", ".join(f"`{n}` ({frac*100:.0f}% empty)" for n, frac in v.empty_columns)
        lines.append(f"- **Mostly-empty columns:** {names}")
    if v.constant_columns:
        lines.append(
            f"- **Constant columns (one value):** {', '.join(f'`{c}`' for c in v.constant_columns)}"
        )
    coercion = [
        (c.cleaned_name, c.n_coercion_failed)
        for c in result.schema.columns
        if c.n_coercion_failed
    ]
    if coercion:
        for name, n in coercion:
            lines.append(f"- **Coercion warning:** `{name}` had {n} unpar-seable value(s).")
    if result.warnings:
        for w in result.warnings:
            lines.append(f"- {w}")
    if not (v.empty_columns or v.constant_columns or coercion or result.warnings):
        lines.append("- No structural issues detected.")
    lines.append("")

    if result.rules is not None:
        lines.append("## Applied rules")
        lines.append("")
        lines.append(f"- Rules file: `{result.config.rules_path}`")
        lines.append("")

    lines.append("## Limitations & privacy")
    lines.append("")
    lines.append(
        "- This tool cleans **one rectangular survey table** (one row per "
        "response). It does not do statistical analysis."
    )
    lines.append(
        "- Type inference is heuristic and threshold-based "
        f"(>= {TYPE_THRESHOLD:.0%} of non-missing values must match). Always "
        "review this report before analysis."
    )
    lines.append(
        "- Runs fully locally. No data is sent to any cloud service or LLM. "
        "The original input file is never modified."
    )
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_cleaning_log(result: ProcessResult, out: Path) -> Path:
    path = out / "cleaning_log.json"
    lr = result.load_result
    v = result.validation
    cfg = result.config

    columns_log = []
    for col in result.schema.columns:
        columns_log.append(
            {
                "original_name": col.original_name,
                "cleaned_name": col.cleaned_name,
                "inferred_type": col.inferred_type,
                "forced_type": col.forced_type,
                "is_multiselect": col.is_multiselect,
                "dropped": col.dropped,
                "n_missing": col.n_missing,
                "pct_missing": col.pct_missing,
                "n_unique": col.n_unique,
                "n_missing_standardised": col.n_missing_standardised,
                "n_coercion_failed": col.n_coercion_failed,
                "split_children": [name for _, name in col.split_children],
                "notes": col.notes,
            }
        )

    log = {
        "tool": "survey-data-cleaner",
        "version": __version__,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "input": {
            "path": lr.source_path,
            "kind": lr.kind,
            "sheet": lr.sheet,
            "encoding": lr.encoding,
            "delimiter": lr.delimiter,
            "n_rows": lr.n_rows,
            "n_cols": lr.n_cols,
        },
        "profile": result.profile.name,
        "config": {
            "profile": cfg.profile,
            "split_multiselect": cfg.split_multiselect,
            "dayfirst": cfg.dayfirst,
            "drop_duplicates": cfg.drop_duplicates,
            "drop_empty_cols": cfg.drop_empty_cols,
            "missing_threshold": cfg.missing_threshold,
            "report_only": cfg.report_only,
            "write_xlsx": cfg.write_xlsx,
            "rules_path": cfg.rules_path,
        },
        "thresholds": {
            "type_match": TYPE_THRESHOLD,
            "categorical_max_unique": CATEGORICAL_MAX_UNIQUE,
            "multiselect_min_delimiter_fraction": MULTISELECT_MIN_DELIM_FRACTION,
            "empty_column": cfg.missing_threshold,
        },
        "missing_tokens": result.missing_tokens,
        "rows_in": result.n_rows_in,
        "rows_out": result.n_rows_out,
        "duplicates": {
            "found": v.n_duplicate_rows,
            "dropped": result.dropped_duplicate_rows,
            "indices": v.duplicate_row_indices,
        },
        "empty_columns": [name for name, _ in v.empty_columns],
        "constant_columns": v.constant_columns,
        "dropped_empty_columns": result.dropped_empty_columns,
        "columns": columns_log,
        "warnings": result.warnings,
    }
    path.write_text(json.dumps(log, indent=2, ensure_ascii=False), encoding="utf-8")
    return path
